name: Compile and upload code
on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: ${{ secrets.DOCKERHUB_USERNAME }}/iot_team:latest
        credentials:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Build program using PIO CLI
      run: |
        pio run
