name: Compile and upload code

on:
  push:
    branches:
      - main

jobs:
  compile-code:
    runs-on: ubuntu-latest
    container:
      image: docker pull hugosilva04/iot_team:tagname
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: https://index.docker.io/v2/
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build program using Platformio CLI
        run: pio run
